# Generated by Django 4.1.4 on 2022-12-26 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(max_length=40)),
                ("c_email", models.EmailField(max_length=70)),
                ("c_phone", models.IntegerField()),
                ("c_msg", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Packages",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("package", models.CharField(max_length=100)),
                ("p_image", models.ImageField(upload_to="Package/images")),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Package_details",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_title", models.CharField(max_length=80)),
                ("p_price_per_person", models.IntegerField()),
                ("p_package_days", models.CharField(max_length=50)),
                ("p_travel_through", models.CharField(max_length=100)),
                ("p_phone", models.IntegerField()),
                ("p_provider_name", models.CharField(max_length=50)),
                ("p_provider_address", models.CharField(max_length=120)),
                ("p_full_package_description", models.TextField(max_length=255)),
                ("p_package_image", models.ImageField(upload_to="Package/images")),
                (
                    "p_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Package.packages",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                ("f_id", models.AutoField(primary_key=True, serialize=False)),
                ("f_msg", models.TextField(max_length=255)),
                (
                    "f_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_address", models.CharField(max_length=255)),
                ("booking_phone", models.IntegerField()),
                ("boarding", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("travellers", models.IntegerField()),
                ("room_wise", models.CharField(max_length=50)),
                (
                    "booking_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Package.package_details",
                    ),
                ),
                (
                    "booking_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
